import React from "react";
import Head from "next/head";
import Cartwidget from "./Cartwidget";

export default function Navbar({ title, children }) {
  return (
    <div>
      <Head>
        <title>{title ? title + "- shopping" : "shopping"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className="navbar navbar-expand-lg bg-light">
        <div className="container-fluid">
          <a className="navbar-brand" href="#home">
            Tienda Apple Import
            <img src="/images/Apple.png" className="logoApple"></img>
          </a>
          <button
            className="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarNav"
            aria-controls="navbarNav"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span className="navbar-toggler-icon"></span>
          </button>
          <div className="collapse navbar-collapse justify-content-end" id="navbarNav">
            <ul className="navbar-nav mr-auto">
              <li className="nav-item">
                <a className="nav-link active " aria-current="page" href="#home">
                  Productos
                </a>
              </li>
              <li className="nav-item">
                <a className="nav-link" href="#sale">
                  Sale!
                </a>
              </li>
              <li className="nav-item">
                <a className="nav-link " href="#faq">
                  Como comprar?
                </a>
              </li>
            </ul>
          </div>
        </div>
        <Cartwidget></Cartwidget>
      </nav>
      <main>
            {children}
        </main>
    </div>
  );
}
