const data = {
  products: [
    {
      name: "iPhone 14 - 128GB",
      slug: "iphone-14",
      category: "Iphones",
      image: "/images/Iphone14.jpg",
      price: 1000,
      rating: 4.5,
      countInStock: 20,
      description: "iPhone 14 - 128GB - Colors Midnight, Purple, Starlight, Red, Blue",
    },
    {
      name: "iPhone 13 - 128GB",
      slug: "iphone-13",
      category: "Iphones",
      image: "/images/Iphone13.jpg",
      price: 800,
      rating: 4.3,
      countInStock: 20,
      description: "iPhone 13 - 128GB - Colors Starlight, Midnight, Blue",
    },
    {
      name: "iPad Pro 11 M1 Chip - 128 GB WiFi",
      slug: "ipad-pro",
      category: "Ipads",
      image: "/images/IpadPro.jpg",
      price: 950,
      rating: 4.5,
      countInStock: 20,
      description: "iPad Pro 11 M1 Chip - 128 GB WiFi",
    },
    {
      name: "iPhone SE (3rd Gen) - 64 GB",
      slug: "iphone-se3",
      category: "Iphones",
      image: "/images/IphoneSE.jpg",
      price: 600,
      rating: 4.7,
      countInStock: 20,
      description: "iPhone SE (3rd Gen) - 64 GB",
    },
    {
      name: "MacBook Air 13.6 M2 Chip 256 GB - Midnight",
      slug: "macbook-air",
      category: "Macbooks",
      image: "/images/MacbookAir.jpg",
      price: 1500,
      rating: 4.5,
      countInStock: 20,
      description: "MacBook Air 13.6 M2 Chip 256 GB - Midnight",
    },
    {
      name: "Macbook Pro 13 [MNEH3] M2 - 256 GB - Space Gray",
      slug: "macbook-pro",
      category: "Macbooks",
      image: "/images/MacbookPro.jpg",
      price: 1400,
      rating: 4.4,
      countInStock: 20,
      description: "Macbook Pro 13 [MNEH3] M2 - 256 GB - Space Gray",
    },
  ],
};

export default data;
